#! /usr/bin/env python
# Complete the shebang line above

# Use the print function from Python 3
from __future__ import print_function

import sys
if sys.version_info[0] > 2:
    INPUT = input
else:
    INPUT = raw_input

statements = {'bob' :  "How about that local sports team?",
              'sally' : "If you were a tree, what kind of tree would you be?",
              'terry' : "Do you know the way to San Jose?",
              'graham' : "I'll have the spam and eggs.",
              'jane' : "I'll have the green eggs and spam."}

defaultStatement = "What is the airspeed velocity of an unladen swallow?"

while True:

    # Get name
    name = INPUT("What is your name? ")

    # If no name is given, exit
    if not name:
        break

    # Name should always start with a capital letter
    formattedName = name.capitalize()

    # Determine which statement to use, statements are below
    # This should work the same regardless of capitalization
    statement = statements.get(name.lower(), defaultStatement)

    print('Hi, %s! %s' % (formattedName, statement))

# Statements to output for specific users
# Bob - How about that local sports team?
# Sally - If you were a tree, what kind of tree would you be?
# Terry - Do you know the way to San Jose?
# Graham - I'll have the spam and eggs.
# Jane - I'll have the green eggs and spam.
# anyone else - What is the airspeed velocity of an unladen swallow?
